name: Extract Mod Offsets
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Unzip Headers File (With Password)
        # تمت إضافة -P 1 لإدخال كلمة السر الخاصة بالملف
        run: unzip -P 1 headers.zip -d ./

      - name: Run Extraction Script
        run: python extract_headers.py

      - name: Upload JSON Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Offsets-JSON
          path: extracted_offsets.json
